name: Flujo de trabajo para ejecutar los test, publica el artefacto y enviar email

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GGITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GGITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el código
        run: |
          chmod +x gradlew
          ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GGITHUB_TOKEN}}
      GITHUB_OAUTH: ${{ secrets.GGITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Probando el código
        run: |
          chmod +x gradlew
          ./gradlew test

  publish:
    runs-on: ubuntu-latest
    needs: test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Publicando el artefacto
        run: |
          chmod +x gradlew
          ./gradlew publish
          echo 'Publicando nuevo artefacto'

  email:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Enviando correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Publicación nuevo artefacto
          to: ${{ secrets.MAIL_DEST }}
          from: Luke Skywalker # <user@example.com>
          body: Se ha publicado un nuevo artefacto
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
